### ISSUE TITLE
Component does not fail gracefully when a section title cannot be found

### ISSUE THREAD

**Issue by robframpton** [metal/metal-reading-progress#2]
https://github.com/metal/metal-reading-progress/blob/master/src/ReadingProgress.js#L35

When this querySelector returns null an error is thrown. It would be nice if it either passes an empty string as the title or throws a more helpful error.

**Comment by eduardolundgren** [comment]
Yep. /cc @fernandosouza you guys can go a head and push a fix for it.

**Comment by fernandosouza** [comment]
Sorry for the delay, @eduardolundgren. I'm going to take a look.
